version: '3'

services:
  apache:
    image: httpd:2.4
    environment:
      TZ: Europe/Moscow
    volumes:
      - ./:/var/www/html
      - ./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php-fpm

  nginx:
    image: nginx:1.21.5
    environment:
      TZ: Europe/Moscow
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache

  php-fpm:
    environment:
      TZ: Europe/Moscow
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:14.1
    ports:
      - '5432:5432'
    volumes:
      - db_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: education_user
      POSTGRES_PASSWORD: edu1135622
      POSTGRES_DB: education_base
      TZ: Europe/Moscow

volumes:
  db_storage:
    driver: local
